version: '3.8'
services:
  postgres:
    image: postgres:15
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y postgresql-15-pgvector &&
        docker-entrypoint.sh postgres
      "
    environment:
      - POSTGRES_DB=faq_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3cr3t
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
